# Generated by Django 5.1.1 on 2024-10-29 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommunitySupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('glycaemic_index', models.FloatField()),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.foodcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GlycaemicResponseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.TextField()),
                ('response_patterns', models.TextField(blank=True, null=True)),
                ('meal_log', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_trackers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HypoHyperGlycaemiaAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_level', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherence_data', models.TextField(blank=True, null=True)),
                ('medication_list', models.ManyToManyField(to='core.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_trackers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('glucose_level', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meal_context', models.CharField(choices=[('fasting', 'Fasting'), ('pre_meal', 'Pre-Meal'), ('post_meal', 'Post-Meal')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='core_glucos_user_id_8516be_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('glucose_level__gte', 0)), name='glucose_level_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('mealId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('food_items', models.ManyToManyField(related_name='meals', to='core.fooditem')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.glycaemicresponsetracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tracker'], name='core_meal_tracker_8026f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VirtualHealthCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_patterns', models.TextField(blank=True, default='')),
                ('motivational_messages', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('motivational_messages__isnull', False)), name='motivational_messages_not_null')],
            },
        ),
    ]
