# Generated by Django 5.1.1 on 2024-10-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medication_communitysupport_glucoselog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucosepredictionmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='virtualdiabeteseducator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='virtualhealthcoach',
            name='activity_logs',
        ),
        migrations.RemoveField(
            model_name='virtualhealthcoach',
            name='health_goals',
        ),
        migrations.RemoveField(
            model_name='virtualhealthcoach',
            name='progress_data',
        ),
        migrations.RemoveField(
            model_name='virtualhealthcoach',
            name='recommendation_model',
        ),
        migrations.AddField(
            model_name='virtualhealthcoach',
            name='user_patterns',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitysupport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glucoselog',
            name='meal_context',
            field=models.CharField(choices=[('fasting', 'Fasting'), ('pre_meal', 'Pre-Meal'), ('post_meal', 'Post-Meal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='glucoselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='glycaemicresponsetracker',
            name='meal_log',
        ),
        migrations.AlterField(
            model_name='glycaemicresponsetracker',
            name='response_patterns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glycaemicresponsetracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glycaemicresponsetracker',
            name='user_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hypohyperglycaemiaalert',
            name='alert_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hypohyperglycaemiaalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.glycaemicresponsetracker'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicationtracker',
            name='adherence_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='virtualhealthcoach',
            name='motivational_messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualhealthcoach',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='glucoselog',
            index=models.Index(fields=['user'], name='core_glucos_user_id_8516be_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['tracker'], name='core_meal_tracker_8026f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='glucoselog',
            constraint=models.CheckConstraint(condition=models.Q(('glucose_level__gte', 0)), name='glucose_level_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='virtualhealthcoach',
            constraint=models.CheckConstraint(condition=models.Q(('motivational_messages__isnull', False)), name='motivational_messages_not_null'),
        ),
        migrations.DeleteModel(
            name='GlucosePredictionModel',
        ),
        migrations.DeleteModel(
            name='VirtualDiabetesEducator',
        ),
        migrations.AddField(
            model_name='glycaemicresponsetracker',
            name='meal_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
