# Generated by Django 5.1.1 on 2024-10-29 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fooditem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glycaemicresponsetracker',
            name='meal_log',
        ),
        migrations.RemoveField(
            model_name='glycaemicresponsetracker',
            name='user_data',
        ),
        migrations.AddField(
            model_name='glycaemicresponsetracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 29, 23, 41, 6, 836468, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glycaemicresponsetracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
