# Generated by Django 5.1.1 on 2024-10-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_glucosepredictionmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucoselog',
            name='id',
        ),
        migrations.AddField(
            model_name='glucoselog',
            name='logID',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
