# Generated by Django 5.1.1 on 2024-11-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foodcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('glycaemic_index', models.FloatField()),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.foodcategory')),
            ],
        ),
    ]
