# Generated by Django 5.1.1 on 2024-10-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_glycaemicresponsetracker_meal_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucoselog',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.meal'),
        ),
        migrations.AddField(
            model_name='glycaemicresponsetracker',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='response_trackers_meals', to='core.meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals_related', to='core.glycaemicresponsetracker'),
        ),
    ]
