# Generated by Django 5.1.1 on 2024-11-10 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('mealId', models.AutoField(primary_key=True, serialize=False)),
                ('user_meal_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('food_items', models.ManyToManyField(related_name='meals', to='core.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'user_meal_id')},
            },
        ),
    ]
