# Generated by Django 5.1.1 on 2024-11-10 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlycaemicResponseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_patterns', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meals', models.ManyToManyField(blank=True, related_name='response_trackers_meals', to='core.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_trackers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
