# Generated by Django 5.1.1 on 2024-11-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_glycaemicresponsetracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualHealthCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_patterns', models.TextField(blank=True, default='')),
                ('motivational_messages', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('motivational_messages__isnull', False)), name='motivational_messages_not_null')],
            },
        ),
    ]
