# Generated by Django 5.1.1 on 2024-11-10 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherence_data', models.TextField(blank=True, null=True)),
                ('medication_list', models.ManyToManyField(to='core.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_trackers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
