# Generated by Django 5.1.1 on 2024-11-21 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_communitysupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeelingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('good', 'Good'), ('okay', 'Okay'), ('bad', 'Bad')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
