# Generated by Django 5.1.1 on 2024-11-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feelingcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('feeling_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_questions', to='core.feelingcheck')),
            ],
        ),
    ]
