# Generated by Django 5.1.1 on 2024-12-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_symptomcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_level', models.FloatField()),
                ('target_min', models.FloatField()),
                ('target_max', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_checks', to='core.questionnairesession')),
            ],
        ),
    ]
