# Generated by Django 5.1.1 on 2024-12-14 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_glucosecheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=10)),
                ('skipped_meals', models.JSONField(blank=True, default=list)),
                ('wellness_impact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('high_gi_foods', models.ManyToManyField(related_name='meal_checks', to='core.fooditem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_checks', to='core.questionnairesession')),
            ],
        ),
    ]
