# Generated by Django 5.1.1 on 2025-01-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_mealcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_exercise_time', models.CharField(choices=[('Today', 'Today'), ('2-3 Days Ago', '2–3 Days Ago'), ('More than 5 Days Ago', 'More than 5 Days Ago'), ('I Don’t Remember', 'I Don’t Remember')], max_length=20)),
                ('exercise_type', models.CharField(choices=[('Walking', 'Walking'), ('Running', 'Running'), ('Yoga', 'Yoga'), ('Strength Training', 'Strength Training'), ('Other', 'Other')], max_length=30)),
                ('exercise_duration', models.PositiveIntegerField()),
                ('post_exercise_feeling', models.CharField(choices=[('Energised', 'Energised'), ('Neutral', 'Neutral'), ('Tired', 'Tired')], max_length=20)),
                ('activity_level_comparison', models.CharField(choices=[('More', 'More'), ('Less', 'Less'), ('About the Same', 'About the Same')], max_length=20)),
                ('activity_prevention_reason', models.CharField(blank=True, choices=[('Lack of time', 'Lack of time'), ('Fatigue', 'Fatigue'), ('Physical discomfort', 'Physical discomfort'), ('Other', 'Other')], max_length=50, null=True)),
                ('discomfort_or_fatigue', models.BooleanField(default=False)),
                ('discomfort_description', models.TextField(blank=True, null=True)),
                ('exercise_impact', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_checks', to='core.questionnairesession')),
            ],
        ),
    ]
