# Generated by Django 5.1.1 on 2025-01-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_exercisecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcheck',
            name='meal_type',
        ),
    ]
