# Generated by Django 5.1.1 on 2025-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_mealcheck_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecheck',
            name='exercise_intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Vigorous', 'Vigorous')], default='Moderate', max_length=20),
        ),
    ]
