# Generated by Django 5.1.1 on 2025-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_exercisecheck_exercise_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecheck',
            name='last_exercise_time',
            field=models.CharField(choices=[('Today', 'Today'), ('2-3 Days Ago', '2-3 Days Ago'), ('More than 5 Days Ago', 'More than 5 Days Ago'), ('I Don’t Remember', 'I Don’t Remember')], max_length=20),
        ),
    ]
