# Generated by Django 5.1.1 on 2025-01-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_exercisecheck_last_exercise_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_checks', to='core.questionnairesession'),
        ),
    ]
