# Generated by Django 5.1.1 on 2025-01-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_mealcheck_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomcheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_check', to='core.questionnairesession'),
        ),
    ]
