# Generated by Django 5.1.1 on 2025-01-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_symptomcheck_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosecheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_check', to='core.questionnairesession'),
        ),
    ]
