# Generated by Django 5.1.1 on 2025-01-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_glucosecheck_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcheck',
            name='high_gi_foods',
            field=models.ManyToManyField(related_name='meal_check', to='core.fooditem'),
        ),
        migrations.AlterField(
            model_name='mealcheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_check', to='core.questionnairesession'),
        ),
    ]
