# Generated by Django 5.1.1 on 2025-01-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_mealcheck_high_gi_foods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecheck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_check', to='core.questionnairesession'),
        ),
    ]
