# Generated by Django 5.1.1 on 2025-01-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_exercisecheck_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairesession',
            name='current_step',
        ),
    ]
