# Generated by Django 5.1.1 on 2025-01-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_questionnairesession_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomcheck',
            name='responses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='routine_change',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='stress',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
