# Generated by Django 5.1.1 on 2025-02-06 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_symptomcheck_responses_symptomcheck_routine_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('glucose_level', models.FloatField(blank=True, null=True)),
                ('glucose_unit', models.CharField(default='mg/dL', max_length=10)),
                ('exercise_type', models.CharField(blank=True, max_length=100, null=True)),
                ('exercise_duration', models.IntegerField(blank=True, null=True)),
                ('exercise_intensity', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
