# Generated by Django 5.1.1 on 2025-02-14 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_smartwatchactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('Smartwatch', 'Smartwatch'), ('Phone', 'Phone'), ('Manual Entry', 'Manual Entry')], default='Smartwatch', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('sleep_stage', models.CharField(blank=True, choices=[('Light Sleep', 'Light Sleep'), ('Deep Sleep', 'Deep Sleep'), ('REM Sleep', 'REM Sleep'), ('Unspecified', 'Unspecified')], max_length=50, null=True)),
                ('total_sleep_hours', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('last_activity_time', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='SmartwatchActivity',
        ),
        migrations.AddIndex(
            model_name='fitnessactivity',
            index=models.Index(fields=['start_time'], name='core_fitnes_start_t_1eacd9_idx'),
        ),
    ]
