# Generated by Django 5.1.1 on 2025-02-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_fitnessactivity_delete_smartwatchactivity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseRecommendation',
        ),
    ]
