# Generated by Django 5.1.1 on 2025-02-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delete_exerciserecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation_text', models.TextField()),
                ('glucose_level', models.FloatField(blank=True, null=True)),
                ('glucose_unit', models.CharField(default='mg/dL', max_length=10)),
                ('context_summary', models.TextField(blank=True, null=True)),
                ('ai_version', models.CharField(default='GPT-4', max_length=20)),
                ('fitness_activities', models.ManyToManyField(blank=True, to='core.fitnessactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
