# Generated by Django 5.1.1 on 2025-02-16 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_localnotificationprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHealthTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('avg_glucose_level', models.FloatField(blank=True, null=True)),
                ('avg_steps', models.IntegerField(blank=True, null=True)),
                ('avg_sleep_hours', models.FloatField(blank=True, null=True)),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('total_exercise_sessions', models.IntegerField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='health_trend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aihealthtrend'),
        ),
    ]
