# Generated by Django 5.1.1 on 2025-03-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_medication_last_taken_medication_rxnorm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onesignalplayerid',
            name='user',
        ),
        migrations.AddField(
            model_name='fitnessactivity',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CustomUserToken',
        ),
        migrations.DeleteModel(
            name='OneSignalPlayerID',
        ),
    ]
