# Generated by Django 5.1.1 on 2025-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_onesignalplayerid_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessactivity',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
