# Generated by Django 5.1.1 on 2025-04-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_fitnessactivity_is_fallback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessactivity',
            old_name='distance_meters',
            new_name='distance_km',
        ),
    ]
