# Generated by Django 5.1.1 on 2025-04-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_forumcategory_forumthread_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='rxnorm_id',
        ),
        migrations.AddField(
            model_name='medication',
            name='fda_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
