# Generated by Django 5.1.1 on 2025-04-11 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_medication_rxnorm_id_medication_fda_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypohyperglycaemiaalert',
            name='user',
        ),
        migrations.CreateModel(
            name='PersonalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CommunitySupport',
        ),
        migrations.DeleteModel(
            name='HypoHyperGlycaemiaAlert',
        ),
    ]
