# Generated by Django 5.1.1 on 2025-04-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_hypohyperglycaemiaalert_user_personalinsight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInsight',
        ),
    ]
