# Generated by Django 5.1.1 on 2025-04-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='review',
            field=models.JSONField(default=list),
        ),
    ]
