# Generated by Django 5.1.1 on 2025-04-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_quizattempt_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feelingcheck',
            name='feeling',
            field=models.CharField(choices=[('bad', 'Bad')], max_length=20),
        ),
    ]
