# Generated by Django 5.1.1 on 2025-04-12 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_feelingcheck_feeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
