# Generated by Django 5.1.1 on 2025-04-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_predictivefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivefeedback',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
    ]
