# Generated by Django 5.1.1 on 2025-04-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_predictivefeedback_model_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivefeedback',
            name='feedback_type',
            field=models.CharField(choices=[('shap', 'SHAP-based'), ('trend', 'Trend-based'), ('improvement', 'Improvement')], default='shap', max_length=20),
            preserve_default=False,
        ),
    ]
