# Generated by Django 5.1.1 on 2025-04-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_predictivefeedback_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihealthtrend',
            name='ai_summary_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
