# Generated by Django 5.1.1 on 2025-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_aihealthtrend_ai_summary_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='repeat_weeks',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='duration',
            field=models.PositiveIntegerField(default=4, help_text='Total duration of reminder in frequency units'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='interval',
            field=models.PositiveIntegerField(default=1, help_text='Repeat every X days/weeks/months'),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LocalNotificationPrompt',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
