# Generated by Django 5.1.1 on 2025-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
