# Generated by Django 5.1.1 on 2025-04-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_forumthread_pinned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUpQuestion',
        ),
    ]
